package com.dmitriyevseyev.carmanager2.server.dao;

import com.dmitriyevseyev.carmanager2.shared.Constants;

import java.sql.*;

public class DAOManager {
    public static java.sql.Connection connection;
    public static DAOManager instance;
    private DAOCar daoCar;
    private DAOUser daoUser;

    public static DAOManager getInstance() {
        if (instance == null) {
            instance = new DAOManager();
        }
        return instance;
    }

    public DAOCar getDaoCar() {
        return daoCar;
    }

    public DAOUser getDaoUser() {
        return daoUser;
    }

    public DAOManager() {

        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection(
                    Constants.JDBC,
                    Constants.USER,
                    Constants.PASSWORD);
            this.daoCar = DAOCar.getInstance(connection);
            this.daoUser = DAOUser.getInstance(connection);

        } catch (SQLException | ClassNotFoundException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        System.out.println("Opened database successfully");

        try (Statement stmt = connection.createStatement()) {
            String sqlCar = "CREATE TABLE IF NOT EXISTS CAR" +
                    "(ID INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                    " NAME           VARCHAR     NOT NULL, " +
                    " DATE           DATE        NOT NULL, " +
                    " COLOR          VARCHAR     NOT NULL, " +
                    " ISAFTERCRASH   BOOLEAN)";
            stmt.executeUpdate(sqlCar);

            String sqlUser = "CREATE TABLE IF NOT EXISTS USERS" +
                    "(ID INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                    " USERNAME       VARCHAR     NOT NULL, " +
                    " PASSWORD       VARCHAR     NOT NULL)";
            stmt.executeUpdate(sqlUser);
            System.out.println("Users");

        } catch (SQLException e) {
            System.err.println("createTableCarError. " + e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }

        /*try (Statement stmt = connection.createStatement()) {
            String sqlUser = "CREATE TABLE IF NOT EXISTS USER" +
                    "(ID INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                    " USERNAME       VARCHAR     NOT NULL, " +
                    " PASSWORD       VARCHAR     NOT NULL)";
            stmt.executeUpdate(sqlUser);
        } catch (SQLException e) {
            System.out.println("DDDDD. " + e.getMessage());
            //System.err.println("createTableUserrError. " + e.getClass().getName() + ": " + e.getMessage());
            //System.exit(0);
        }

         */
    }
}

